### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by ebisbe** [Saeris/Flickr-Wormhole#6]
Hey! 
I read your article explaining this project and thought I would give it a try. I read that it's not all implemented. I don't have any experience in grapQL so thats why I'm here asking you if you could guide me to implement the groups endpoint. Articles, videos whatevere. 

I've been looking throught the src and I see that all api definitions are set up inside methods ( I asume that they are all from flickr. Do you know they have an official one working? flickr-sdk it's called.

Then I see that at least to things have to be done:

- Implement auth 
- Define groups model and types?

good work!

**Comment by Saeris** [comment]
Hey there! Sorry for the delayed response. Glad to hear you read the article!

So to implement an endpoint like `Groups`, first thing you would need to do is go through the REST endpoints related to groups in Flickr's API and inspect the responses to determine what the shape of the data models related to them are.

A quick glance indicates to me that you would at least need a `Group` model to describe a group's name, description, member count, etc, a `Topic` model, a `Reply` model, possibly a `Member` model, etc.

Once you've determined what the data models are, that's when you can start building your type definitions around them, transforming the data as you see necessary. This might just mean renaming some fields to be more consistent across your API, it may mean adding new fields to fetch related data (ie: mapping `Member`s to `User`s), and it could also mean reformatting the response data into something more usable, such as converting dates.

As for flickr-sdk, I did take a look at it, but I didn't particularly like the way they wrote it. Ultimately what it came down to was, I had already been putting together a library to make REST calls to Flickr, so it wasn't too hard to just keep fleshing that out. I'll definitely take a closer look at flickr-sdk to see how they're handling authorization though.

Hopefully I'll be able to devote some more time to this project next month. I'll be out most of this week.

Thanks for submitting the PR btw! I need to look into why Travis is failing all of a sudden.

**Comment by ebisbe** [comment]
Thanks for the response. I have manage to implement the Group call. I'll dig more into how to set up types, resolvers, loaders more corretly and then I'll try to implement the Auth. 

One thing with the configuration of eslint. I'm using phpstorm and it doesn't recognises the ?. operator. Do you know a way to configure your set up correctly? I have to waste time trying no to broke the indentation.

Thanks

**Comment by Saeris** [comment]
The `?.` operator is a stage-1 syntax proposal, so it doesn't have a lot of support yet. This is likely a problem with phpstorm specifically in how it handles linting with eslint, not with eslint itself. But I'm not entirely sure either. I use atom for all of my development. I don't really know how to help you there.

**Comment by ebisbe** [comment]
I've installed Atom and a bunch of packages. Any special one to use? The esling in atom now recognizes ?. operator but I'm having issues with Beautifying code. Can you share what to you use?

By the way. I've updated and added the flickr-sdk because I need to work with some auth endpoints. Once I have some more endpoints I'll make a PR

**Comment by Saeris** [comment]
Primarily I use prettier to do beautification. A lot of the eslint fix rules are applied as a pre-commit hook.

Not sure if you'll be able to see it, but I use an atom package called sync-settings that backs up all my installed packages and settings to a gist, which you can look at here:

https://gist.github.com/Saeris/f738dc07abd27cae8466f3ae58aadf64

You won't be able to use that to restore from yourself, probably have to clone the gist in order to use it. But anyways it has a list of all my installed packages. Also be aware that I'm using some custom fonts which you likely will not have installed.

I'd rather not pull in the flickr-sdk. If you wanted to use it in your fork that's fine however. I didn't really intend for there to be major outside contributions to this project right now. Appreciate the offer to help though!
